name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: echo '{"credHelpers":{"ghcr.io":"ghcr"}}' > ~/.docker/config.json
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - run: mkdir -p ~/.local/bin
      - run: echo 'echo "{"ServerURL":"ghcr.io","Username":"Bearer","Secret":"${{ secrets.GITHUB_TOKEN }}"}"' > ~/.local/bin/docker-credential-ghcr
      - run: chmod +x ~/bin/.local/docker-credential-ghcr
      - run: bazel build //cmd/ocitool:ocitool && cp bazel-bin/cmd/ocitool/ocitool_/ocitool bin/ocitool-linux-amd64
      - run: bazel test //...
